package Oracle::XS::HexConverter;

use strict;
use warnings;

our $VERSION = '0.01';

use XSLoader;
XSLoader::load(__PACKAGE__, $VERSION);

1;

__END__

=head1 NAME

Oracle::XS::HexConverter - High performance hex string to binary converter

=head1 SYNOPSIS

    use Oracle::XS::HexConverter;
    my $hex_ref = \"41424344";
    my $binary  = Oracle::XS::HexConverter::hex_to_binary($hex_ref);
    # $binary now contains "ABCD"

=head1 DESCRIPTION

This module provides a single function, C<hex_to_binary>, which accepts a
reference to a scalar containing an ASCII hexadecimal string and returns
a binary string.  It uses SSSE3 intrinsics to convert blocks of 32
characters at a time for maximum throughput.  Remaining characters are
handled via a lookup table.  If the input contains an odd number of
characters or an invalid hex digit, an exception is thrown.

=head1 FUNCTIONS

=head2 hex_to_binary

    my $binary = Oracle::XS::HexConverter::hex_to_binary(\$hex_string);

Converts the hexadecimal string pointed at by the reference into its
binary form and returns it as a Perl scalar.  The input scalar must
only contain ASCII characters; if the scalar is flagged as UTF‑8 it is
downgraded to bytes using C<sv_utf8_downgrade>【817665102442637†L378-L404】.  An exception is thrown if the
string cannot be downgraded or if it contains invalid characters.

=head1 AUTHOR

Generated by ChatGPT.

=cut